### ISSUE TITLE
Improving the README.md

### ISSUE THREAD

**Issue by PirxDanford** [moritzheiber/devops-at-thoughtworks-presentation#1]
Hi,

as I had no ruby environment and did not want to install I just used a Docker container.

It would be a bit easier if you could improve your steps to work out of the box.

My steps were:
- docker run -p 8000:8000 -it --rm mwendler/ruby.tiny.rake /bin/sh
- apk update && apk add git
- git clone https://github.com/moritzheiber/devops-at-thoughtworks-presentation.git /demo
- cd /demo
- bundle install --path vendor/bundle
- bundle exec rake webserver

P.S. Maybe you want to provide your own container instead of the mwendler/ruby.tiny.rake - then you could include a script to install and run everything directly

P.P.S. As I also had no Docker installed on my Windows 10 Home machine I used the instructions from https://stackoverflow.com/questions/54387049/installing-docker-on-windows-10-home-can-it-be-done - which work like a charm and with this I have a Hyper-V enabled Docker on Windows Home :-D

**Comment by moritzheiber** [comment]
@PirxDanford I'll look into creating my own Docker image with the presentation in it. Good call, and thank you for the suggestions!

**Comment by moritzheiber** [comment]
@PirxDanford I've created a Docker container with pretty much the same specifications as you mentioned in this issue. You can follow the steps in the README. Thanks!
